// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM1CS6xoiVoy5mUUo9I3BdDtYHGSeAUkQ',
    appId: '1:990256393407:web:871a3c4745d92fc77e6a0a',
    messagingSenderId: '990256393407',
    projectId: 'project-eticket-pas',
    authDomain: 'project-eticket-pas.firebaseapp.com',
    storageBucket: 'project-eticket-pas.appspot.com',
    measurementId: 'G-T74F42TVV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0pZZigqUCtGFc7sEquFVNlC2tB-DMt-I',
    appId: '1:990256393407:android:a5885a61925442ab7e6a0a',
    messagingSenderId: '990256393407',
    projectId: 'project-eticket-pas',
    storageBucket: 'project-eticket-pas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfad_MesfGcElvrfG7y4aeCo39ac6BrY4',
    appId: '1:990256393407:ios:887329f6590f253d7e6a0a',
    messagingSenderId: '990256393407',
    projectId: 'project-eticket-pas',
    storageBucket: 'project-eticket-pas.appspot.com',
    iosBundleId: 'com.example.projectPasBusEticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfad_MesfGcElvrfG7y4aeCo39ac6BrY4',
    appId: '1:990256393407:ios:887329f6590f253d7e6a0a',
    messagingSenderId: '990256393407',
    projectId: 'project-eticket-pas',
    storageBucket: 'project-eticket-pas.appspot.com',
    iosBundleId: 'com.example.projectPasBusEticket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM1CS6xoiVoy5mUUo9I3BdDtYHGSeAUkQ',
    appId: '1:990256393407:web:bd76f5a8b07668857e6a0a',
    messagingSenderId: '990256393407',
    projectId: 'project-eticket-pas',
    authDomain: 'project-eticket-pas.firebaseapp.com',
    storageBucket: 'project-eticket-pas.appspot.com',
    measurementId: 'G-GBRL33V1FF',
  );
}